# Network settings
network.bind_host: 0.0.0.0
cluster.name: elasticsearch
node.name: "elastic_test_node"
cluster.routing.allocation.disk.watermark.low: "95%"
cluster.routing.allocation.disk.watermark.high: "95%"
discovery.zen.minimum_master_nodes: 1
script.inline: on
script.indexed: on
script.engine.groovy.inline.aggs: on

